version: "3"

x-env_file: &web
  env_file:
    - web.env

include:
  - proxy.yaml

services:
  web:
    build:
      dockerfile:  Dockerfile.python
      context: .
    <<: [*web]
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      - db
    networks:
        backend:
          ipv4_address: 172.20.0.5

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    env_file:
      - db.env
    volumes:
      - ./dbdata:/var/lib/mysql/
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.10

networks:
  backend:
    driver: bridge
    ipam:
     config:
      - subnet: 172.20.0.0/24
